import { Inter } from "next/font/google";
import "./globals.css";
import Sidebar from "@/components/Sidebar";
import { ThemeProvider } from "@/provider/ThemeProvider";
import Navbar from "@/components/Navbar";

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Property Management",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html suppressHydrationWarning lang="en">
      <body className={`${inter.className} antialiased`}>
        <ThemeProvider enableSystem={false} attribute="class">
          <div className="h-screen w-full bg-background overflow-hidden">
            <Navbar />
            <div className="flex gap-x-5 h-full">
              <Sidebar />
              <div className="p-5 flex-1 bg-[#f3f3f3] dark:bg-contentBackground h-full w-full overflow-y-auto">
                {children}
              </div>
            </div>
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
